In [1]:
# stop showing warnings.
import warnings
warnings.filterwarnings("ignore")
# import numpy library
import numpy as np

In [2]:
# Create an array from 1 to 10
arr1 = np.arange(1, 11)
print(f"Array from 1 to 10: {arr1}")

Array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:

# Create a 2D array with 4 rows and 3 columns
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(f"2D array with shape (4,3): {arr2}")

2D array with shape (4,3): [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Create a 3D array with shape (2,2,3)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"3D array with shape (2,2,3): {arr3}")

3D array with shape (2,2,3): [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
